import SwiftUI
import ImageIO

// A `Pin*` view's own description of how it renders, in design-token terms — generated by
// the `@Pinnable` macro from the component's declaration, so authors annotate instead of
// hand-writing the mapping. Design facts only (token names, radius, typography); any
// Figma/other mapping lives in the consumer.
public struct PinComponentStyle {
    public let name: String
    public let text: String?
    public let textStyle: PinTextStyle?
    public let textColorTokenName: String?
    public let fillTokenName: String?
    // Resolved colors used when there's no token (a `.custom(text:background:)` style); the
    // capture emits them raw so the fill/text aren't dropped to nothing.
    public let textColor: Color?
    public let fillColor: Color?
    public let cornerRadius: CGFloat?
    public let centersText: Bool
    public let underline: Bool
    // `false` dims the captured node, matching a disabled control.
    public let enabled: Bool

    public init(
        name: String,
        text: String?,
        textStyle: PinTextStyle?,
        textColorTokenName: String?,
        fillTokenName: String?,
        textColor: Color? = nil,
        fillColor: Color? = nil,
        cornerRadius: CGFloat?,
        centersText: Bool,
        underline: Bool = false,
        enabled: Bool = true
    ) {
        self.name = name
        self.text = text
        self.textStyle = textStyle
        self.textColorTokenName = textColorTokenName
        self.fillTokenName = fillTokenName
        self.textColor = textColor
        self.fillColor = fillColor
        self.cornerRadius = cornerRadius
        self.centersText = centersText
        self.underline = underline
        self.enabled = enabled
    }

    /// A copy under a different capture name. Components use it to give each visual variant its own
    /// name so distinct-looking instances don't collapse onto one Figma master.
    public func named(_ name: String) -> PinComponentStyle {
        PinComponentStyle(
            name: name, text: text, textStyle: textStyle, textColorTokenName: textColorTokenName,
            fillTokenName: fillTokenName, textColor: textColor, fillColor: fillColor,
            cornerRadius: cornerRadius, centersText: centersText, underline: underline, enabled: enabled
        )
    }
}

/// A token that names itself for capture, so the `name` mapping lives on the token once
/// rather than in every component. `@PinFill`/`@PinColor` read these.
public protocol PinFillToken {
    var captureFillToken: String? { get }
    // The raw fill when the style resolves to no token (e.g. `.custom`); `nil` when a token covers it.
    var captureFillColor: Color? { get }
}

public protocol PinTextColorToken {
    var captureTextColorToken: String? { get }
    var captureTextColor: Color? { get }
}

public extension PinFillToken {
    var captureFillColor: Color? { nil }
}

public extension PinTextColorToken {
    var captureTextColor: Color? { nil }
}

public struct PinCapturedComponent {
    public let style: PinComponentStyle
    public let bounds: Anchor<CGRect>
    // Base64 PNG for rasterized nodes — native controls, images, SF Symbols — that have no
    // structured descriptor. `nil` for `@Pinnable` components, which rebuild from `style`.
    public let image: String?
    public let isContainer: Bool
    public let needsRasterization: Bool
    public let layout: PinCaptureLayout?

    public init(
        style: PinComponentStyle, bounds: Anchor<CGRect>, image: String? = nil,
        isContainer: Bool = false, needsRasterization: Bool = false, layout: PinCaptureLayout? = nil
    ) {
        self.style = style
        self.bounds = bounds
        self.image = image
        self.isContainer = isContainer
        self.needsRasterization = needsRasterization
        self.layout = layout
    }
}

public struct PinCaptureLayout {
    public enum Axis { case row, column }
    public enum CrossAxis { case leading, center, trailing }
    public let axis: Axis
    public let spacing: CGFloat
    public let padding: EdgeInsets
    public let spaceBetween: Bool
    public let alignment: CrossAxis
    // A floor a hugging container keeps, so a short-content instance doesn't reflow below the real
    // control's minimum (a `PinButton`'s 100pt titled width).
    public let minWidth: CGFloat?

    public init(axis: Axis, spacing: CGFloat, padding: EdgeInsets = EdgeInsets(), spaceBetween: Bool = false, alignment: CrossAxis = .center, minWidth: CGFloat? = nil) {
        self.axis = axis
        self.spacing = spacing
        self.padding = padding
        self.spaceBetween = spaceBetween
        self.alignment = alignment
        self.minWidth = minWidth
    }
}

public extension EnvironmentValues {
    /// Set by a capture host so lazy containers (`PinList`) lay out every row eagerly; off-screen
    /// rows emit no capture descriptors otherwise.
    @Entry var pinCapturing: Bool = false

    /// A sink the catalog calls with a displayed component's id, its captured descriptors, and the
    /// layout proxy — so a consumer can capture-on-view (e.g. push to a Figma serve) with no button.
    @Entry var pinCaptureSink: (@MainActor (String, [PinCapturedComponent], GeometryProxy) -> Void)? = nil
}

public struct PinCaptureKey: PreferenceKey {
    public static let defaultValue: [PinCapturedComponent] = []
    public nonisolated static func reduce(value: inout [PinCapturedComponent], nextValue: () -> [PinCapturedComponent]) {
        value.append(contentsOf: nextValue())
    }
}

public extension View {
    func pinCaptured(_ style: PinComponentStyle) -> some View {
        anchorPreference(key: PinCaptureKey.self, value: .bounds) { anchor in
            [PinCapturedComponent(style: style, bounds: anchor)]
        }
    }

    /// Marks this view a capture group (a list row) that nests the captured nodes inside its bounds.
    /// `transformAnchorPreference` *appends* the container; plain `anchorPreference` would replace the
    /// descendants' captured nodes (the row's own labels) with just this one.
    func pinCapturedContainer(name: String, fillTokenName: String? = nil, fillColor: Color? = nil, cornerRadius: CGFloat? = nil, enabled: Bool = true, layout: PinCaptureLayout? = nil) -> some View {
        transformAnchorPreference(key: PinCaptureKey.self, value: .bounds) { value, anchor in
            value.append(PinCapturedComponent(
                style: PinComponentStyle(
                    name: name, text: nil, textStyle: nil, textColorTokenName: nil,
                    fillTokenName: fillTokenName, fillColor: fillColor, cornerRadius: cornerRadius,
                    centersText: false, enabled: enabled
                ),
                bounds: anchor,
                isContainer: true,
                layout: layout
            ))
        }
    }

    func pinCapturedRasterized(name: String, image: String? = nil) -> some View {
        transformAnchorPreference(key: PinCaptureKey.self, value: .bounds) { value, anchor in
            value.append(PinCapturedComponent(
                style: PinComponentStyle(
                    name: name, text: nil, textStyle: nil, textColorTokenName: nil,
                    fillTokenName: nil, cornerRadius: nil, centersText: false
                ),
                bounds: anchor,
                image: image,
                // A pre-rendered image needs no window crop; only mark for it when we lack one.
                needsRasterization: image == nil
            ))
        }
    }

    /// Rasterizes a pure-SwiftUI view off-screen for capture instead of cropping the live window.
    /// Deterministic and transparent — the crop races layout and bakes in whatever is behind the
    /// view, so a thin/small element (a spinner) captures blank or as a mismatched square.
    @MainActor func pinCapturedRendered(name: String, scale: CGFloat = 3) -> some View {
        pinCapturedRasterized(name: name, image: PinCaptureRasterizer.base64PNG(of: self, scale: scale))
    }
}

@MainActor
enum PinCaptureRasterizer {
    static func base64PNG<Content: View>(of view: Content, scale: CGFloat) -> String? {
        let renderer = ImageRenderer(content: view)
        renderer.scale = scale
        guard let cgImage = renderer.cgImage else { return nil }
        let data = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(data, "public.png" as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(destination, cgImage, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return (data as Data).base64EncodedString()
    }
}
