import SwiftUI

// A `Pin*` view's own description of how it renders, in design-token terms — generated by
// the `@Pinnable` macro from the component's declaration, so authors annotate instead of
// hand-writing the mapping. Design facts only (token names, radius, typography); any
// Figma/other mapping lives in the consumer.
public struct PinComponentStyle {
    public let name: String
    public let text: String?
    public let textStyle: PinTextStyle?
    public let textColorTokenName: String?
    public let fillTokenName: String?
    public let cornerRadius: CGFloat?
    public let centersText: Bool

    public init(
        name: String,
        text: String?,
        textStyle: PinTextStyle?,
        textColorTokenName: String?,
        fillTokenName: String?,
        cornerRadius: CGFloat?,
        centersText: Bool
    ) {
        self.name = name
        self.text = text
        self.textStyle = textStyle
        self.textColorTokenName = textColorTokenName
        self.fillTokenName = fillTokenName
        self.cornerRadius = cornerRadius
        self.centersText = centersText
    }
}

/// A token that names itself for capture, so the `name` mapping lives on the token once
/// rather than in every component. `@PinFill`/`@PinColor` read these.
public protocol PinFillToken {
    var captureFillToken: String? { get }
}

public protocol PinTextColorToken {
    var captureTextColorToken: String? { get }
}

public struct PinCapturedComponent {
    public let style: PinComponentStyle
    public let bounds: Anchor<CGRect>
    // Base64 PNG for rasterized nodes — native controls, images, SF Symbols — that have no
    // structured descriptor. `nil` for `@Pinnable` components, which rebuild from `style`.
    public let image: String?
    public let isContainer: Bool
    public let needsRasterization: Bool
    public let layout: PinCaptureLayout?

    public init(
        style: PinComponentStyle, bounds: Anchor<CGRect>, image: String? = nil,
        isContainer: Bool = false, needsRasterization: Bool = false, layout: PinCaptureLayout? = nil
    ) {
        self.style = style
        self.bounds = bounds
        self.image = image
        self.isContainer = isContainer
        self.needsRasterization = needsRasterization
        self.layout = layout
    }
}

public struct PinCaptureLayout {
    public enum Axis { case row, column }
    public enum CrossAxis { case leading, center, trailing }
    public let axis: Axis
    public let spacing: CGFloat
    public let padding: EdgeInsets
    public let spaceBetween: Bool
    public let alignment: CrossAxis

    public init(axis: Axis, spacing: CGFloat, padding: EdgeInsets = EdgeInsets(), spaceBetween: Bool = false, alignment: CrossAxis = .center) {
        self.axis = axis
        self.spacing = spacing
        self.padding = padding
        self.spaceBetween = spaceBetween
        self.alignment = alignment
    }
}

public extension EnvironmentValues {
    /// Set by a capture host so lazy containers (`PinList`) lay out every row eagerly; off-screen
    /// rows emit no capture descriptors otherwise.
    @Entry var pinCapturing: Bool = false
}

public struct PinCaptureKey: PreferenceKey {
    public static let defaultValue: [PinCapturedComponent] = []
    public nonisolated static func reduce(value: inout [PinCapturedComponent], nextValue: () -> [PinCapturedComponent]) {
        value.append(contentsOf: nextValue())
    }
}

public extension View {
    func pinCaptured(_ style: PinComponentStyle) -> some View {
        anchorPreference(key: PinCaptureKey.self, value: .bounds) { anchor in
            [PinCapturedComponent(style: style, bounds: anchor)]
        }
    }

    /// Marks this view a capture group (a list row) that nests the captured nodes inside its bounds.
    /// `transformAnchorPreference` *appends* the container; plain `anchorPreference` would replace the
    /// descendants' captured nodes (the row's own labels) with just this one.
    func pinCapturedContainer(name: String, fillTokenName: String? = nil, cornerRadius: CGFloat? = nil, layout: PinCaptureLayout? = nil) -> some View {
        transformAnchorPreference(key: PinCaptureKey.self, value: .bounds) { value, anchor in
            value.append(PinCapturedComponent(
                style: PinComponentStyle(
                    name: name, text: nil, textStyle: nil, textColorTokenName: nil,
                    fillTokenName: fillTokenName, cornerRadius: cornerRadius, centersText: false
                ),
                bounds: anchor,
                isContainer: true,
                layout: layout
            ))
        }
    }

    func pinCapturedRasterized(name: String) -> some View {
        transformAnchorPreference(key: PinCaptureKey.self, value: .bounds) { value, anchor in
            value.append(PinCapturedComponent(
                style: PinComponentStyle(
                    name: name, text: nil, textStyle: nil, textColorTokenName: nil,
                    fillTokenName: nil, cornerRadius: nil, centersText: false
                ),
                bounds: anchor,
                needsRasterization: true
            ))
        }
    }
}
