import SwiftUI

// A `Pin*` view's own description of how it renders, in design-token terms — generated by
// the `@Pinnable` macro from the component's declaration, so authors annotate instead of
// hand-writing the mapping. Design facts only (token names, radius, typography); any
// Figma/other mapping lives in the consumer.
public struct PinComponentStyle {
    public let name: String
    public let text: String?
    public let textStyle: PinTextStyle?
    public let textColorTokenName: String?
    public let fillTokenName: String?
    public let cornerRadius: CGFloat?
    public let centersText: Bool

    public init(
        name: String,
        text: String?,
        textStyle: PinTextStyle?,
        textColorTokenName: String?,
        fillTokenName: String?,
        cornerRadius: CGFloat?,
        centersText: Bool
    ) {
        self.name = name
        self.text = text
        self.textStyle = textStyle
        self.textColorTokenName = textColorTokenName
        self.fillTokenName = fillTokenName
        self.cornerRadius = cornerRadius
        self.centersText = centersText
    }
}

/// A token that names itself for capture, so the `name` mapping lives on the token once
/// rather than in every component. `@PinFill`/`@PinColor` read these.
public protocol PinFillToken {
    var captureFillToken: String? { get }
}

public protocol PinTextColorToken {
    var captureTextColorToken: String? { get }
}

public struct PinCapturedComponent {
    public let style: PinComponentStyle
    public let bounds: Anchor<CGRect>
}

public struct PinCaptureKey: PreferenceKey {
    public static let defaultValue: [PinCapturedComponent] = []
    public nonisolated static func reduce(value: inout [PinCapturedComponent], nextValue: () -> [PinCapturedComponent]) {
        value.append(contentsOf: nextValue())
    }
}

public extension View {
    func pinCaptured(_ style: PinComponentStyle) -> some View {
        anchorPreference(key: PinCaptureKey.self, value: .bounds) { anchor in
            [PinCapturedComponent(style: style, bounds: anchor)]
        }
    }
}
